server:
  port: 8888
spring:
  application:
    name: springboot-study
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  #数据库连接配置  使用阿里数据库连接池
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      name: druidDataSource
      druid:
        url: jdbc:mysql://192.168.86.128:3306/studydb?useSSL=false
        username: root
        password: 1qaz@WSX
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,log4j,config             #配置监控统计拦截的filters，去掉后监控界面SQL无法进行统计，’wall’用于防火墙
        max-active: 2000        #最大连接数
        initial-size: 5       #初始化大小
        min-idle: 2           #最小连接数
        max-wait: 3000       #获取连接等待超时时间
        time-between-eviction-runs-millis: 60000      #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 25200000        #一个连接在池中最小生存的时间，单位是毫秒
        validation-query: select 'X'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 50
        max-pool-prepared-statement-per-connection-size: 20
  #redis相关配置
  redis:
    #单机模式的配置
    host: 192.168.86.128  #Redis服务器地址
    database: 0     #Redis数据库索引（默认为0）
    port: 6393      #Redis服务器连接端口
#    password:       #Redis服务器连接密码
    jedis:
      pool:
        max-active: 500 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10    #连接池中的最大空闲连接
        min-idle: 5     #连接池中的最小空闲连接
    timeout: 1000       #连接超时时间（毫秒）
    #集群模式的配置
#    cluster:
#      nodes:
#        - 192.168.86.128:6389
#        - 192.168.86.128:6390
#        - 192.168.86.128:6391
#        - 192.168.86.128:6392
#thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false          #热部署文件，页面不产生缓存，及时更新
#热部署生效
  devtools:
    restart:
      enabled: true
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude:

logging:
  level:
    root: info
    com.neusoft.study: trace
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  global-config:
    db-config:
      id-type: id_worker

